---
- name: Check service started/stopped
  block:
    - name: Check service started/stopped
      service:
        name: "{{ assert_service.name }}"
        state: "{{ 'started' if assert_service.is_running else 'stopped' }}"
      check_mode: true
      register: result
    - name: Assert service started/stopped
      assert:
        that: result is not changed
        success_msg: "サービス「{{ assert_service.name }}」は稼働して{{ 'います' if assert_service.is_running else 'いません' }}"
        fail_msg: "サービス「{{ assert_service.name }}」が稼働して{{ 'いません' if assert_service.is_running else 'しています' }}"
  when: assert_service.is_running is boolean
- name: Check service enabled/disabled
  block:
    - name: Check service enabled/disabled
      service:
        name: "{{ assert_service.name }}"
        enabled: "{{ assert_service.is_enabled }}"
      check_mode: true
      register: result
    - name: Assert service enabled/disabled
      assert:
        that: result is not changed
        success_msg: "サービス「{{ assert_service.name }}」は{{ '有効化されています' if assert_service.is_enabled | default(true) else '無効化されています' }}"
        fail_msg: "サービス「{{ assert_service.name }}」が{{ '無効化されています' if assert_service.is_enabled | default(true) else '有効化されています' }}"
  when: assert_service.is_enabled is boolean
