---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: assert groups
      include_role:
        name: assert
        tasks_from: group
      vars:
        assert_group:
          name: "{{ item.name }}"
      loop: "{{ test_groups }}"
    - name: assert users
      include_role:
        name: assert
        tasks_from: user
      vars:
        assert_user:
          name: "{{ item.name }}"
      loop: "{{ test_users }}"
    - name: assert files
      include_role:
        name: assert
        tasks_from: file
      vars:
        assert_file:
          path: "{{ item.path }}"
          exists: true
          is_dir: "{{ true if item.state == 'directory' else omit }}"
          is_file: "{{ true if item.state == 'touch' else omit }}"
          is_symlink: "{{ true if item.state == 'link' else omit }}"
          linked_to: "{{ item.src if item.state == 'link' else omit }}"
      loop: "{{ test_files }}"
    - name: assert packages
      include_role:
        name: assert
        tasks_from: package
      vars:
        assert_package:
          name: "{{ item }}"
      loop:
        - "{{ web_server.package }}"
        - "{{ database_server.package }}"
    - name: assert services
      include_role:
        name: assert
        tasks_from: service
      vars:
        assert_service:
          name: "{{ item }}"
      loop:
        - "{{ web_server.service }}"
        - "{{ database_server.service }}"
    - name: assert ports
      include_role:
        name: assert
        tasks_from: port
      vars:
        assert_port:
          port: "{{ item }}"
      loop:
        - "{{ web_server.port }}"
        - "{{ database_server.port }}"
