---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: install test packages
      package:
        name:
          - "{{ web_server.package }}"
          - "{{ database_server.package }}"
    - name: set service status
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - "{{ web_server.service }}"
        - "{{ database_server.service }}"
    - name: create test files
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        src: "{{ item.src if item.state == 'link' else omit }}"
      loop: "{{ test_files }}"
    - name: assert package
      include_role:
        name: assert
        tasks_from: package
      vars:
        assert_package:
          name: "{{ item }}"
      loop:
        - "{{ web_server.package }}"
        - "{{ database_server.package }}"
    - name: assert service
      include_role:
        name: assert
        tasks_from: service
      vars:
        assert_service:
          name: "{{ item }}"
      loop:
        - "{{ web_server.service }}"
        - "{{ database_server.service }}"
    - name: assert port
      include_role:
        name: assert
        tasks_from: port
      vars:
        assert_port:
          port: "{{ item }}"
      loop:
        - "{{ web_server.port }}"
        - "{{ database_server.port }}"
    - name: assert file
      include_role:
        name: assert
        tasks_from: file
      vars:
        assert_file:
          path: "{{ item.path }}"
          is_dir: "{{ true if item.state == 'directory' else false }}"
          is_file: "{{ true if item.state == 'touch' else false }}"
          is_symlink: "{{ true if item.state == 'link' else false }}"
          linked_to: "{{ item.src if item.state == 'link' else omit }}"
      loop: "{{ test_files }}"
